version: "3.8"
services:
  expressapp:
    container_name: expressapp
    restart: unless-stopped
    build: 
      context: server
      dockerfile: Dockerfile
    ports: 
      - 8080:8080
    networks: 
      - shared-network
  reactapp:
    container_name: reactapp
    build: 
      context: client
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    networks: 
      - shared-network
    depends_on:
      - expressapp
  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports: 
      - 80:80
    networks: 
      - shared-network
    depends_on:
      - reactapp
      - expressapp
networks:
  shared-network:
   
